### ISSUE TITLE
Error: Create Pages site failed

### ISSUE THREAD

**Issue by kangxiaoning** [JetBrains/writerside-github-action#4]
I encountered the following error when deploying GitHub pages.
```
Run actions/configure-pages@v2
  with:
    token: ***
    enablement: true
  env:
    INSTANCE: Writerside/blog
    ARTIFACT: webHelpBLOG[2](https://github.com/kangxiaoning/docs/actions/runs/6577030959/job/17868155477#step:5:2)-all.zip
    DOCKER_VERSION: 2.1.1479-p[3](https://github.com/kangxiaoning/docs/actions/runs/6577030959/job/17868155477#step:5:3)869
    ALGOLIA_ARTIFACT: algolia-indexes-BLOG.zip
  
Warning: Get Pages site failed
Error: Create Pages site failed
Error: AxiosError: Request failed with status code [4](https://github.com/kangxiaoning/docs/actions/runs/6577030959/job/17868155477#step:5:4)03
```

The following is my `deploy.yml` file content.

```
name: Build documentation

on:
  # If specified, the workflow will be triggered automatically once you push to the `main` branch.
  # Replace `main` with your branch’s name
  push:
    branches: ["main"]
  # Specify to run a workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# Gives the workflow permissions to clone the repo and create a page deployment
permissions:
  id-token: write
  pages: write

env:
  # Name of module and id separated by a slash
  INSTANCE: Writerside/blog
  # Replace HI with the ID of the instance in capital letters
  ARTIFACT: webHelpBLOG2-all.zip
  # Writerside docker image version
  DOCKER_VERSION: 2.1.1479-p3869
  # Add the variable below to upload Algolia indexes
  # Replace HI with the ID of the instance in capital letters
  ALGOLIA_ARTIFACT: algolia-indexes-BLOG.zip

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Writerside docs using Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
          retention-days: 7

      # Add the step below to upload Algolia indexes
      - name: Upload algolia-indexes
        uses: actions/upload-artifact@v3
        with:
          name: algolia-indexes
          path: artifacts/${{ env.ALGOLIA_ARTIFACT }}
          retention-days: 7

  # Add the job below and artifacts/report.json on Upload documentation step above if you want to fail the build when documentation contains errors
  test:
    # Requires build job results
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: docs
          path: artifacts

      - name: Test documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Requires the build job results
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docs

      - name: Unzip artifact
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq ${{ env.ARTIFACT }} -d dir

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

```
